(part "SQP20AJB-68R"
    (packageRef "RESAD11000W85L6000D1250")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "603-SQP20AJB-68R")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/YAGEO/SQP20AJB-68R?qs=gt1LBUVyoHl26g7iELFF7A%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "SQP20AJB-68R")
    (property "Description" "68 Ohms +/-5% 20W Through Hole Resistor Axial Flame Proof, Pulse Withstanding, Safety Cement")
    (property "Datasheet_Link" "https://www.yageogroup.com/content/datasheet/asset/file/YAGEO-SQP_NSP_DATASHEET")
    (property "symbolName1" "SQP20AJB-68R")
)
