(part "UF4007"
    (packageRef "DIOAD1413W86L463D238")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Mouser_Part_Number" "512-UF4007")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi-Fairchild/UF4007?qs=NwIfwa72FlplAHiXupLMBA%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "UF4007")
    (property "Description" "High current capability; High reliability ; Low forward voltage drop ; High surge current capability")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/UF4007-D.pdf")
    (property "symbolName1" "UF4007")
)
