(part "22-04-1041"
    (packageRef "SHDR4W64P0X250_1X4_950X580X1210P")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "538-22-04-1041")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Molex/22-04-1041?qs=KHty%2FoMxDPmNq3PD4JOsMQ%3D%3D")
    (property "Manufacturer_Name" "Molex")
    (property "Manufacturer_Part_Number" "22-04-1041")
    (property "Description" "Headers & Wire Housings .098 HDR VERT 4P")
    (property "Datasheet_Link" "https://www.molex.com/pdm_docs/sd/022041041_sd.pdf")
    (property "symbolName1" "22-04-1041")
)
