(part "CY15B102Q-SXET"
    (packageRef "SOIC127P800X203-8N")
    (interface
        (port "1" (symbPinId 1) (portName "%CS%") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SO") (portType INOUT))
        (port "3" (symbPinId 3) (portName "%WP%") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VSS") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SI") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SCK") (portType INOUT))
        (port "7" (symbPinId 7) (portName "%HOLD%") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "727-CY15B102Q-SXET")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Infineon-Technologies/CY15B102Q-SXET?qs=3FnuM6ZipRJPdZOLuRNzcg%3D%3D")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "CY15B102Q-SXET")
    (property "Description" "FRAM 2Mbit Serial-SPI 3.3V Automotive 8-Pin SOIC T/R")
    (property "Datasheet_Link" "https://www.mouser.in/datasheet/2/100/CYPR_S_A0004022923_1-2540860.pdf")
    (property "symbolName1" "CY15B102Q-SXET")
)
