(part "TPS389006ADJRTER"
    (packageRef "QFN50P300X300X80-17N-D")
    (interface
        (port "1" (symbPinId 1) (portName "MON3") (portType INOUT))
        (port "2" (symbPinId 2) (portName "MON6") (portType INOUT))
        (port "3" (symbPinId 3) (portName "MON4") (portType INOUT))
        (port "4" (symbPinId 4) (portName "MON5") (portType INOUT))
        (port "5" (symbPinId 5) (portName "ACT") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GND_1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "%SLEEP%") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VDD") (portType INOUT))
        (port "9" (symbPinId 9) (portName "%SYNC%") (portType INOUT))
        (port "10" (symbPinId 10) (portName "MON2") (portType INOUT))
        (port "11" (symbPinId 11) (portName "RS_1/2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "MON1") (portType INOUT))
        (port "13" (symbPinId 13) (portName "NIRQ") (portType INOUT))
        (port "14" (symbPinId 14) (portName "ADDR") (portType INOUT))
        (port "15" (symbPinId 15) (portName "SDA") (portType INOUT))
        (port "16" (symbPinId 16) (portName "SCL") (portType INOUT))
        (port "17" (symbPinId 17) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS389006ADJRTER")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS389006ADJRTER?qs=1Kr7Jg1SGW%2FXzoFRuc4x8A%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS389006ADJRTER")
    (property "Description" "Supervisory Circuits Multichannel overvoltage and undervoltage IC programmable voltage supervisor 16-WQFN -40 to 125")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/tps389006-q1.pdf?ts=1707388080315&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FTPS389006-Q1")
    (property "symbolName1" "TPS389006ADJRTER")
)
