(part "TBP01R2W-508-06BE"
    (packageRef "SHDR6W100P0X508_1X6_4064X850X1240P")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "490-TBP01R2W-50806BE")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Same-Sky/TBP01R2W-508-06BE?qs=PzGy0jfpSMstd7VozfoB7g%3D%3D")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "TBP01R2W-508-06BE")
    (property "Description" "2~24 Poles, Pluggable, Receptacle, Vertical 5.08 Pitch, Terminal Block Connector")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/supplyframepdf/tbp01r2w-508.pdf")
    (property "symbolName1" "TBP01R2W-508-06BE")
)
