(part "3550150RJT"
    (packageRef "RESC11050X120N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "279-3550150RJT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity-Holsworthy/3550150RJT?qs=gZXFycFWdAPP9JL3CHAw6w%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "3550150RJT")
    (property "Description" "Thick Film Resistors - SMD 3550 150R 5%")
    (property "Datasheet_Link" "")
    (property "symbolName1" "3550150RJT")
)
