(part "UCS2D331MHD"
    (packageRef "CAPPRD750W80D1800H3700")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Nichicon")
    (property "Manufacturer_Part_Number" "UCS2D331MHD")
    (property "Description" "Nichicon 330uF Electrolytic Capacitor 200V dc Through Hole - UCS2D331MHD")
    (property "Datasheet_Link" "https://www.nichicon.co.jp/english/series_items/catalog_pdf/e-ucs.pdf")
    (property "symbolName1" "UCS2D331MHD")
)
