M48
; DRILL file KiCad 10.0.3 date 2026-07-16T15:50:28
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-16T15:50:28-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
%
G90
G05
T1
X26.65Y-5.5
X65.55Y-5.5
X112.95Y-5.5
X151.85Y-5.5
X198.25Y-5.375
X237.15Y-5.375
M30
