(part "STTH112A"
    (packageRef "DIOM5126X265N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Mouser_Part_Number" "511-STTH112A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/STTH112A?qs=1X0wRT6hCqH%2F7s%2FmzYZuyg%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "STTH112A")
    (property "Description" " Low forwarded voltage drop  High reliability  High surge current capability  Soft switching for reduced EMI disturbances  Planar technology")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/stth112.pdf")
    (property "symbolName1" "STTH112A")
)
