(part "PJGBLC03C-AU_R1_000A1"
    (packageRef "PJGBLC03CAU_R1_000A1")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "241-PJGBLC03CAUR1000")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Panjit/PJGBLC03C-AU_R1_000A1?qs=sPbYRqrBIVma558P%2Few%252BiQ%3D%3D")
    (property "Manufacturer_Name" "PANJIT")
    (property "Manufacturer_Part_Number" "PJGBLC03C-AU_R1_000A1")
    (property "Description" "ESD Suppressors / TVS Diodes 3V ESD Protection BI")
    (property "Datasheet_Link" "https://www.panjit.com.tw/upload/datasheet/PJGBLC03-AU_C24C-AU_SERIES.pdf")
    (property "symbolName1" "PJGBLC03C-AU_R1_000A1")
)
