M48
; DRILL file {KiCad 9.0.1} date 2026-02-07T15:36:26-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-07T15:36:26-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X23.5Y-51.0
X266.5Y-51.0
T2
X7.0Y-5.0
X100.0Y-45.0
X190.0Y-45.0
X291.0Y-6.0
M30
