(part "9774030592R"
    (packageRef "9774030592R")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "710-9774030592R")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Wurth-Elektronik/9774030592R?qs=iLbezkQI%252BsiNSOBHLp2x0A%3D%3D")
    (property "Manufacturer_Name" "Wurth Elektronik")
    (property "Manufacturer_Part_Number" "9774030592R")
    (property "Description" "WA-SMSI SMT Steel Spacer, M5 Internal non Stop steel, tin plated with internal thread M5 non stop outer 9.2mm, reduced to 5.8mm on PCB-side for a borehole body length 3.0mm on Reel, with Polyimide Tape")
    (property "Datasheet_Link" "https://www.we-online.com/catalog/datasheet/9774030592R.pdf")
    (property "symbolName1" "9774030592R")
)
