(part "TS40-66-50-R-260-SMT-TR"
    (packageRef "TS406650R260SMTTR")
    (interface
        (port "1" (symbPinId 1) (portName "COM_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NO_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NO_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "TS40-66-50-R-260-SMT-TR")
    (property "Description" "6 x 6 mm, 5 mm Actuator Height Off PCB, 260 gf, Red, Surface Mount, SPST, Tactile Switch")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/ts40.pdf")
    (property "symbolName1" "TS40-66-50-R-260-SMT-TR")
)
