(part "UJ2-B-HR-G-V"
    (packageRef "UJ2BHRGV")
    (interface
        (port "1" (symbPinId 1) (portName "VBUS") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D-") (portType INOUT))
        (port "3" (symbPinId 3) (portName "D+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "MH1" (symbPinId 5) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 6) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "179-UJ2-B-HR-G-V")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/CUI-Devices/UJ2-B-HR-G-V?qs=HoCaDK9Nz5fUWn12FBL%2Fqw%3D%3D")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "UJ2-B-HR-G-V")
    (property "Description" "Type B, USB 2.0, 480 Mbps, 5 Vdc, 1.5 A, Vertical, Through Hole Mounting Style, Through Hole Contact Pin Type. Gold Flash, Board Lock, 4 Pin, USB Receptacle")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/uj2-b-hr-g-v.pdf")
    (property "symbolName1" "UJ2-B-HR-G-V")
)
