(part "B2B-XH-AM_LF__SN_"
    (packageRef "B2BXHAMLFSN")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "306-B2B-XH-AMLFSNP")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/JST-Commercial/B2B-XH-AMLFSN?qs=cdbOS8ANM9BJgHgwB7WxQw%3D%3D")
    (property "Manufacturer_Name" "JST (JAPAN SOLDERLESS TERMINALS)")
    (property "Manufacturer_Part_Number" "B2B-XH-AM(LF)(SN)")
    (property "Description" "CONN HEADER VERT 2POS 2.5MM")
    (property "Datasheet_Link" "https://www.jst-mfg.com/product/pdf/eng/eXH.pdf")
    (property "symbolName1" "B2B-XH-AM_LF__SN_")
)
