(part "STS41A-AWLB-R3"
    (packageRef "STS41AAWLBR3")
    (interface
        (port "1" (symbPinId 1) (portName "SDA") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SCL") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VDD") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VSS") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Sensirion")
    (property "Manufacturer_Part_Number" "STS41A-AWLB-R3")
    (property "Description" "Temperature Sensor Digital, Local -40C ~ 125C 16 b")
    (property "Datasheet_Link" "https://www.mouser.ee/datasheet/3/1278/1/43275AE2DF69B96E1EE51D04FE33A8965C8A26ED3D33DDCB8BA22F99BAA99334.pdf")
    (property "symbolName1" "STS41A-AWLB-R3")
)
