(part "MCP2221A-I_ST"
    (packageRef "SOP65P640X120-14N")
    (interface
        (port "1" (symbPinId 1) (portName "VDD") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GP0") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GP1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "%RST%") (portType INOUT))
        (port "5" (symbPinId 5) (portName "URX") (portType INOUT))
        (port "6" (symbPinId 6) (portName "UTX") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GP2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GP3") (portType INOUT))
        (port "9" (symbPinId 9) (portName "SDA") (portType INOUT))
        (port "10" (symbPinId 10) (portName "SCL") (portType INOUT))
        (port "11" (symbPinId 11) (portName "VUSB") (portType INOUT))
        (port "12" (symbPinId 12) (portName "D-") (portType INOUT))
        (port "13" (symbPinId 13) (portName "D+") (portType INOUT))
        (port "14" (symbPinId 14) (portName "VSS") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "579-MCP2221A-I/ST")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology/MCP2221A-I-ST?qs=ZEMkBHnybREMkqMgzOrcGQ%3D%3D")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "MCP2221A-I/ST")
    (property "Description" "USB 2.0 to I2C/UART Protocol Converter")
    (property "Datasheet_Link" "http://ww1.microchip.com/downloads/en/devicedoc/20005565b.pdf")
    (property "symbolName1" "MCP2221A-I_ST")
)
