(part "FM24V02A-G"
    (packageRef "SOIC127P602X173-8N")
    (interface
        (port "1" (symbPinId 1) (portName "A0") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "A2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VSS") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SDA") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SCL") (portType INOUT))
        (port "7" (symbPinId 7) (portName "WP") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "727-FM24V02A-G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Cypress-Semiconductor/FM24V02A-G/?qs=ILgNtqsyH23xixHZ0uhhNg%3D%3D")
    (property "Manufacturer_Name" "Infineon")
    (property "Manufacturer_Part_Number" "FM24V02A-G")
    (property "Description" "Cypress Semiconductor FM24V02A-G Serial-I2C FRAM Memory, 256kbit, 2  3.6 V SOIC 8-Pin")
    (property "Datasheet_Link" "https://ms.componentsearchengine.com/Datasheets/2/FM24V02A-G.pdf")
    (property "symbolName1" "FM24V02A-G")
)
