(part "ADCM-S05R5SA224XB"
    (packageRef "ADCMS05R5SA224XB")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "ABRACON")
    (property "Manufacturer_Part_Number" "ADCM-S05R5SA224XB")
    (property "Description" "Supercapacitors / Ultracapacitors CAP 0.22F 5.5V THT")
    (property "Datasheet_Link" "https://abracon.com/datasheets/ADCM-S05R5S.pdf")
    (property "symbolName1" "ADCM-S05R5SA224XB")
)
