(part "524265-E"
    (packageRef "524265E")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "MP1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "MP2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "MP3") (portType INOUT))
        (port "10" (symbPinId 10) (portName "MP4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "524265-E")
    (property "Description" "PCB Mount Header, Right Angle, Cable-to-Board, 6 Position, 6.2 mm [.244 in] Centerline, Fully Shrouded, Gold (Au), Surface Mount, ERNI VolTron 1000")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F524266-E%7FA1%7Fpdf%7FEnglish%7FENG_CD_524266-E_A1.pdf%7F524265-E")
    (property "symbolName1" "524265-E")
)
