M48
; DRILL file KiCad 10.0.3 date 2026-07-15T18:13:27
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-15T18:13:27-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X146.65Y-5.975
X156.15Y-5.975
X165.65Y-5.975
T2
X16.125Y-3.15
X16.125Y-42.05
M30
