(part "NCD57100DWR2G"
    (packageRef "SOIC127P1030X265-16N")
    (interface
        (port "1" (symbPinId 1) (portName "VEE2A") (portType INOUT))
        (port "2" (symbPinId 2) (portName "DESAT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "OUTH") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VDD2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUTL") (portType INOUT))
        (port "7" (symbPinId 7) (portName "CLAMP") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VEE2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "GND1A") (portType INOUT))
        (port "10" (symbPinId 10) (portName "IN+") (portType INOUT))
        (port "11" (symbPinId 11) (portName "IN−") (portType INOUT))
        (port "12" (symbPinId 12) (portName "RDY") (portType INOUT))
        (port "13" (symbPinId 13) (portName "%FLT%") (portType INOUT))
        (port "14" (symbPinId 14) (portName "%RST%") (portType INOUT))
        (port "15" (symbPinId 15) (portName "VDD1") (portType INOUT))
        (port "16" (symbPinId 16) (portName "GND1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "863-NCD57100DWR2G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi/NCD57100DWR2G?qs=vvQtp7zwQdOcYrqkXGsoBw%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "NCD57100DWR2G")
    (property "Description" "High Current Output(+/-7 A) at Miller Plateau Voltages; Short Propagation Delays with Accurate Matching; DESAT with Soft Turn Off; Active Miller Clamp and Negative Gate Voltage; High Transient & Electromagnetic Immunity; 5 kV Galvanic Isolation")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/NCD57100-D.PDF")
    (property "symbolName1" "NCD57100DWR2G")
)
